const fs = require('fs');
const path = require('path');
const { app } = require('electron');

const IMAGE_TAG = 'deepwiki-open:desktop';
const PROJECT_NAME = 'deepwiki-desktop';
const API_PORT = 8001;
const FRONTEND_PORT = 3000;

function getAppRoot() {
  return path.join(__dirname, '..');
}

function getComposeFile() {
  if (app.isPackaged) {
    return path.join(process.resourcesPath, 'docker-compose.yml');
  }
  const desktop = path.join(getAppRoot(), 'docker-compose.desktop.yml');
  if (fs.existsSync(desktop)) {
    return desktop;
  }
  return path.join(getAppRoot(), 'docker-compose.yml');
}

function getImageTar() {
  if (app.isPackaged) {
    return path.join(process.resourcesPath, 'deepwiki-open.tar');
  }
  return path.join(__dirname, 'resources', 'deepwiki-open.tar');
}

function getUserDataPaths() {
  const root = app.getPath('userData');
  return {
    root,
    settingsFile: path.join(root, 'settings.json'),
    envFile: path.join(root, '.env'),
    dataDir: path.join(root, 'adalflow'),
    logDir: path.join(root, 'logs'),
  };
}

function toComposePath(p) {
  return p.replace(/\\/g, '/');
}

function ensureUserData() {
  const paths = getUserDataPaths();
  fs.mkdirSync(paths.dataDir, { recursive: true });
  fs.mkdirSync(paths.logDir, { recursive: true });
  if (!fs.existsSync(paths.envFile)) {
    fs.writeFileSync(paths.envFile, defaultEnvContents({}), 'utf8');
  }
  if (!fs.existsSync(paths.settingsFile)) {
    fs.writeFileSync(paths.settingsFile, '{}\n', 'utf8');
  }
  return paths;
}

const ENV_KEYS = [
  'GOOGLE_API_KEY',
  'OPENAI_API_KEY',
  'OPENROUTER_API_KEY',
  'OPENAI_BASE_URL',
  'AZURE_OPENAI_API_KEY',
  'AZURE_OPENAI_ENDPOINT',
  'OLLAMA_HOST',
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_REGION',
  'DEEPWIKI_EMBEDDER_TYPE',
  'DEEPWIKI_AUTH_MODE',
  'DEEPWIKI_AUTH_CODE',
];

function parseEnvFile(contents) {
  const out = {};
  for (const line of String(contents || '').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function defaultEnvContents(values) {
  const v = values || {};
  return `# DeepWiki desktop environment
# Generated by the Electron shell. Edit via in-app settings.

GOOGLE_API_KEY=${v.GOOGLE_API_KEY || ''}
OPENAI_API_KEY=${v.OPENAI_API_KEY || ''}
OPENROUTER_API_KEY=${v.OPENROUTER_API_KEY || ''}
OPENAI_BASE_URL=${v.OPENAI_BASE_URL || ''}
AZURE_OPENAI_API_KEY=${v.AZURE_OPENAI_API_KEY || ''}
AZURE_OPENAI_ENDPOINT=${v.AZURE_OPENAI_ENDPOINT || ''}
OLLAMA_HOST=${v.OLLAMA_HOST || ''}
AWS_ACCESS_KEY_ID=${v.AWS_ACCESS_KEY_ID || ''}
AWS_SECRET_ACCESS_KEY=${v.AWS_SECRET_ACCESS_KEY || ''}
AWS_REGION=${v.AWS_REGION || ''}
DEEPWIKI_EMBEDDER_TYPE=${v.DEEPWIKI_EMBEDDER_TYPE || 'openai'}
DEEPWIKI_AUTH_MODE=${v.DEEPWIKI_AUTH_MODE || 'false'}
DEEPWIKI_AUTH_CODE=${v.DEEPWIKI_AUTH_CODE || ''}
PORT=8001
NODE_ENV=production
SERVER_BASE_URL=http://localhost:8001
LOG_LEVEL=INFO
`;
}

function readSettings() {
  const { settingsFile, envFile } = ensureUserData();
  let settings = {};
  try {
    settings = JSON.parse(fs.readFileSync(settingsFile, 'utf8') || '{}');
  } catch {
    settings = {};
  }
  const env = parseEnvFile(fs.readFileSync(envFile, 'utf8'));
  const keys = {};
  for (const key of ENV_KEYS) {
    keys[key] = env[key] || '';
  }
  return {
    keys,
    stopContainersOnQuit: settings.stopContainersOnQuit !== false,
    locale: settings.locale || '',
  };
}

function writeSettings(next) {
  const paths = ensureUserData();
  const current = readSettings();
  const mergedKeys = { ...current.keys, ...(next.keys || {}) };
  fs.writeFileSync(paths.envFile, defaultEnvContents(mergedKeys), 'utf8');
  const settings = {
    stopContainersOnQuit:
      next.stopContainersOnQuit ?? current.stopContainersOnQuit,
    locale: next.locale ?? current.locale,
  };
  fs.writeFileSync(paths.settingsFile, JSON.stringify(settings, null, 2), 'utf8');
  return readSettings();
}

function hasAnyApiKey(keys) {
  const k = keys || {};
  return Boolean(
    k.GOOGLE_API_KEY ||
      k.OPENAI_API_KEY ||
      k.OPENROUTER_API_KEY ||
      k.AZURE_OPENAI_API_KEY ||
      k.OLLAMA_HOST
  );
}

module.exports = {
  IMAGE_TAG,
  PROJECT_NAME,
  API_PORT,
  FRONTEND_PORT,
  getAppRoot,
  getComposeFile,
  getImageTar,
  getUserDataPaths,
  toComposePath,
  ensureUserData,
  ENV_KEYS,
  readSettings,
  writeSettings,
  hasAnyApiKey,
};
