const fs = require('fs');
const path = require('path');
const { app } = require('electron');

const API_PORT = 8001;
const FRONTEND_PORT = 3000;

function getAppRoot() {
  return path.join(__dirname, '..');
}

function getRuntimeRoot() {
  if (app.isPackaged) {
    return process.resourcesPath;
  }
  return path.join(__dirname, 'resources');
}

function getPythonExe() {
  return path.join(getRuntimeRoot(), 'python', 'python.exe');
}

function getNodeExe() {
  return path.join(getRuntimeRoot(), 'node', 'node.exe');
}

function getGitExe() {
  return path.join(getRuntimeRoot(), 'git', 'cmd', 'git.exe');
}

function getApiRoot() {
  if (app.isPackaged) {
    return path.join(getRuntimeRoot(), 'api');
  }
  return path.join(getAppRoot(), 'api');
}

function getWebRoot() {
  return path.join(getRuntimeRoot(), 'web');
}

function getUserDataPaths() {
  const root = app.getPath('userData');
  return {
    root,
    settingsFile: path.join(root, 'settings.json'),
    envFile: path.join(root, '.env'),
    dataDir: path.join(root, '.adalflow'),
    logDir: path.join(root, 'logs'),
    configDir: path.join(root, 'config'),
  };
}

function ensureUserData() {
  const paths = getUserDataPaths();
  fs.mkdirSync(paths.dataDir, { recursive: true });
  fs.mkdirSync(paths.logDir, { recursive: true });
  fs.mkdirSync(paths.configDir, { recursive: true });
  if (!fs.existsSync(paths.envFile)) {
    fs.writeFileSync(paths.envFile, defaultEnvContents({}), 'utf8');
  }
  if (!fs.existsSync(paths.settingsFile)) {
    fs.writeFileSync(paths.settingsFile, '{}\n', 'utf8');
  }
  return paths;
}

const ENV_KEYS = [
  'OPENAI_API_KEY',
  'OPENAI_BASE_URL',
  'OPENAI_MODEL',
  'OPENAI_EMBEDDING_MODEL',
  'GOOGLE_API_KEY',
  'OPENROUTER_API_KEY',
  'AZURE_OPENAI_API_KEY',
  'AZURE_OPENAI_ENDPOINT',
  'OLLAMA_HOST',
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_REGION',
  'DEEPWIKI_EMBEDDER_TYPE',
  'DEEPWIKI_AUTH_MODE',
  'DEEPWIKI_AUTH_CODE',
];

function parseEnvFile(contents) {
  const out = {};
  for (const line of String(contents || '').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

const DEFAULT_LOCAL_EMBEDDING_MODEL = 'BAAI/bge-small-en-v1.5';

function resolveLocalEmbeddingModel(name) {
  const value = String(name || '').trim();
  if (!value) return DEFAULT_LOCAL_EMBEDDING_MODEL;
  const lower = value.toLowerCase();
  if (
    lower.startsWith('text-embedding') ||
    lower.includes('gemini-embedding') ||
    lower.includes('titan-embed') ||
    lower === 'nomic-embed-text'
  ) {
    return DEFAULT_LOCAL_EMBEDDING_MODEL;
  }
  return value;
}

function normalizeBaseUrl(url) {
  let value = String(url || '').trim();
  if (!value) return '';
  value = value.replace(/\/+$/, '');
  if (!/\/v\d+/i.test(value)) {
    value += '/v1';
  }
  return value;
}

function defaultEnvContents(values) {
  const v = values || {};
  const baseUrl = normalizeBaseUrl(v.OPENAI_BASE_URL);
  return `# DeepWiki desktop environment
# Generated by the Electron shell. Edit via in-app settings.

OPENAI_BASE_URL=${baseUrl}
OPENAI_API_KEY=${v.OPENAI_API_KEY || ''}
OPENAI_MODEL=${v.OPENAI_MODEL || ''}
OPENAI_EMBEDDING_MODEL=${resolveLocalEmbeddingModel(v.OPENAI_EMBEDDING_MODEL)}
DEEPWIKI_EMBEDDER_TYPE=local
GOOGLE_API_KEY=${v.GOOGLE_API_KEY || ''}
OPENROUTER_API_KEY=${v.OPENROUTER_API_KEY || ''}
AZURE_OPENAI_API_KEY=${v.AZURE_OPENAI_API_KEY || ''}
AZURE_OPENAI_ENDPOINT=${v.AZURE_OPENAI_ENDPOINT || ''}
OLLAMA_HOST=${v.OLLAMA_HOST || ''}
AWS_ACCESS_KEY_ID=${v.AWS_ACCESS_KEY_ID || ''}
AWS_SECRET_ACCESS_KEY=${v.AWS_SECRET_ACCESS_KEY || ''}
AWS_REGION=${v.AWS_REGION || ''}
DEEPWIKI_AUTH_MODE=${v.DEEPWIKI_AUTH_MODE || 'false'}
DEEPWIKI_AUTH_CODE=${v.DEEPWIKI_AUTH_CODE || ''}
PORT=8001
NODE_ENV=production
SERVER_BASE_URL=http://127.0.0.1:8001
LOG_LEVEL=INFO
`;
}

function writeDesktopModelConfig(keys) {
  const paths = ensureUserData();
  const bundled = path.join(getApiRoot(), 'config');
  for (const name of ['lang.json', 'repo.json']) {
    const from = path.join(bundled, name);
    const to = path.join(paths.configDir, name);
    if (fs.existsSync(from) && !fs.existsSync(to)) {
      fs.copyFileSync(from, to);
    }
  }

  const model = String(keys.OPENAI_MODEL || '').trim() || 'gpt-4o';
  const embeddingModel = resolveLocalEmbeddingModel(keys.OPENAI_EMBEDDING_MODEL);

  const generator = {
    default_provider: 'openai',
    providers: {
      openai: {
        default_model: model,
        client_class: 'OpenAIClient',
        supportsCustomModel: true,
        models: {
          [model]: {
            temperature: 0.7,
            top_p: 0.8,
          },
        },
      },
    },
  };
  fs.writeFileSync(
    path.join(paths.configDir, 'generator.json'),
    `${JSON.stringify(generator, null, 2)}\n`,
    'utf8'
  );

  const embedder = {
    embedder: {
      client_class: 'OpenAIClient',
      initialize_kwargs: {
        api_key: '${OPENAI_API_KEY}',
        base_url: '${OPENAI_BASE_URL}',
      },
      batch_size: 10,
      model_kwargs: {
        model: embeddingModel,
      },
    },
    embedder_local: {
      client_class: 'LocalEmbedderClient',
      batch_size: 32,
      model_kwargs: {
        model: embeddingModel,
      },
    },
    retriever: { top_k: 20 },
    text_splitter: {
      split_by: 'word',
      chunk_size: 350,
      chunk_overlap: 100,
    },
  };
  fs.writeFileSync(
    path.join(paths.configDir, 'embedder.json'),
    `${JSON.stringify(embedder, null, 2)}\n`,
    'utf8'
  );

  return paths.configDir;
}

function readSettings() {
  const { settingsFile, envFile } = ensureUserData();
  let settings = {};
  try {
    settings = JSON.parse(fs.readFileSync(settingsFile, 'utf8') || '{}');
  } catch {
    settings = {};
  }
  const env = parseEnvFile(fs.readFileSync(envFile, 'utf8'));
  const keys = {};
  for (const key of ENV_KEYS) {
    keys[key] = env[key] || '';
  }
  if (keys.OPENAI_BASE_URL) {
    keys.OPENAI_BASE_URL = normalizeBaseUrl(keys.OPENAI_BASE_URL);
  }
  return {
    keys,
    stopServicesOnQuit:
      settings.stopServicesOnQuit ?? settings.stopContainersOnQuit !== false,
    locale: settings.locale || '',
  };
}

function writeSettings(next) {
  const paths = ensureUserData();
  const current = readSettings();
  const mergedKeys = { ...current.keys, ...(next.keys || {}) };
  if (mergedKeys.OPENAI_BASE_URL) {
    mergedKeys.OPENAI_BASE_URL = normalizeBaseUrl(mergedKeys.OPENAI_BASE_URL);
  }
  mergedKeys.OPENAI_EMBEDDING_MODEL = resolveLocalEmbeddingModel(
    mergedKeys.OPENAI_EMBEDDING_MODEL
  );
  mergedKeys.DEEPWIKI_EMBEDDER_TYPE = 'local';
  fs.writeFileSync(paths.envFile, defaultEnvContents(mergedKeys), 'utf8');
  writeDesktopModelConfig(mergedKeys);
  const settings = {
    stopServicesOnQuit: next.stopServicesOnQuit ?? current.stopServicesOnQuit,
    locale: next.locale ?? current.locale,
  };
  fs.writeFileSync(paths.settingsFile, JSON.stringify(settings, null, 2), 'utf8');
  return readSettings();
}

function hasModelConnection(keys) {
  const k = keys || {};
  return Boolean(
    String(k.OPENAI_BASE_URL || '').trim() &&
      String(k.OPENAI_API_KEY || '').trim() &&
      String(k.OPENAI_MODEL || '').trim()
  );
}

module.exports = {
  API_PORT,
  FRONTEND_PORT,
  getAppRoot,
  getRuntimeRoot,
  getPythonExe,
  getNodeExe,
  getGitExe,
  getApiRoot,
  getWebRoot,
  getUserDataPaths,
  ensureUserData,
  ENV_KEYS,
  normalizeBaseUrl,
  writeDesktopModelConfig,
  readSettings,
  writeSettings,
  hasModelConnection,
  hasAnyApiKey: hasModelConnection,
  DEFAULT_LOCAL_EMBEDDING_MODEL,
  resolveLocalEmbeddingModel,
};
